Baza_zapasow/Models/WypozyczenieTV.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza_zapasow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WypozyczenieTV
    {
        public int WypozyczenieTVID { get; set; }
        public Nullable<System.DateTime> DataWypozyczenia { get; set; }
        public Nullable<System.DateTime> DataZwrotu { get; set; }
        public Nullable<int> TelewizorID { get; set; }
        public string Dodatkowo { get; set; }
        public string Opis { get; set; }
    
        public virtual Telewizory Telewizory { get; set; }
    }
}

Baza_zapasow/Controllers/TelewizoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Baza_zapasow.Models;

namespace Baza_zapasow.Controllers
{
    public class TelewizoryController : Controller
    {
        private Zapasy_bazaEntities db = new Zapasy_bazaEntities();

        // GET: Telewizory
        public ActionResult Index()
        {
            return View(db.Telewizory.ToList());
        }

        // GET: Telewizory/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Telewizory telewizory = db.Telewizory.Find(id);
            if (telewizory == null)
            {
                return HttpNotFound();
            }
            return View(telewizory);
        }

        // GET: Telewizory/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Telewizory/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TelewizorID,Nazwa,Rozmiar")] Telewizory telewizory)
        {
            if (ModelState.IsValid)
            {
                db.Telewizory.Add(telewizory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(telewizory);
        }

        // GET: Telewizory/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Telewizory telewizory = db.Telewizory.Find(id);
            if (telewizory == null)
            {
                return HttpNotFound();
            }
            return View(telewizory);
        }

        // POST: Telewizory/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TelewizorID,Nazwa,Rozmiar")] Telewizory telewizory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(telewizory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(telewizory);
        }

        // GET: Telewizory/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Telewizory telewizory = db.Telewizory.Find(id);
            if (telewizory == null)
            {
                return HttpNotFound();
            }
            return View(telewizory);
        }

        // POST: Telewizory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Telewizory telewizory = db.Telewizory.Find(id);
            db.Telewizory.Remove(telewizory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Baza_zapasow/Controllers/WypozyczenieTVController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Baza_zapasow.Models;

namespace Baza_zapasow.Controllers
{
    public class WypozyczenieTVController : Controller
    {
        private Zapasy_bazaEntities db = new Zapasy_bazaEntities();

        // GET: WypozyczenieTV
        public ActionResult Index()
        {
            var wypozyczenieTV = db.WypozyczenieTV.Include(w => w.Telewizory);
            return View(wypozyczenieTV.ToList());
        }

        // GET: WypozyczenieTV/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WypozyczenieTV wypozyczenieTV = db.WypozyczenieTV.Find(id);
            if (wypozyczenieTV == null)
            {
                return HttpNotFound();
            }
            return View(wypozyczenieTV);
        }

        // GET: WypozyczenieTV/Create
        public ActionResult Create()
        {
            ViewBag.TelewizorID = new SelectList(db.Telewizory, "TelewizorID", "Nazwa");
            return View();
        }

        // POST: WypozyczenieTV/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "WypozyczenieTVID,DataWypozyczenia,DataZwrotu,TelewizorID,Dodatkowo,Opis")] WypozyczenieTV wypozyczenieTV)
        {
            if (ModelState.IsValid)
            {
                db.WypozyczenieTV.Add(wypozyczenieTV);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TelewizorID = new SelectList(db.Telewizory, "TelewizorID", "Nazwa", wypozyczenieTV.TelewizorID);
            return View(wypozyczenieTV);
        }

        // GET: WypozyczenieTV/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WypozyczenieTV wypozyczenieTV = db.WypozyczenieTV.Find(id);
            if (wypozyczenieTV == null)
            {
                return HttpNotFound();
            }
            ViewBag.TelewizorID = new SelectList(db.Telewizory, "TelewizorID", "Nazwa", wypozyczenieTV.TelewizorID);
            return View(wypozyczenieTV);
        }

        // POST: WypozyczenieTV/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "WypozyczenieTVID,DataWypozyczenia,DataZwrotu,TelewizorID,Dodatkowo,Opis")] WypozyczenieTV wypozyczenieTV)
        {
            if (ModelState.IsValid)
            {
                db.Entry(wypozyczenieTV).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TelewizorID = new SelectList(db.Telewizory, "TelewizorID", "Nazwa", wypozyczenieTV.TelewizorID);
            return View(wypozyczenieTV);
        }

        // GET: WypozyczenieTV/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WypozyczenieTV wypozyczenieTV = db.WypozyczenieTV.Find(id);
            if (wypozyczenieTV == null)
            {
                return HttpNotFound();
            }
            return View(wypozyczenieTV);
        }

        // POST: WypozyczenieTV/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            WypozyczenieTV wypozyczenieTV = db.WypozyczenieTV.Find(id);
            db.WypozyczenieTV.Remove(wypozyczenieTV);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Baza_zapasow/Views/WypozyczenieTV/Create.cshtml
@model Baza_zapasow.Models.WypozyczenieTV

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>WypozyczenieTV</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DataWypozyczenia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataWypozyczenia, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.DataWypozyczenia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataZwrotu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataZwrotu, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.DataZwrotu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TelewizorID, "TelewizorID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TelewizorID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TelewizorID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dodatkowo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dodatkowo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dodatkowo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Opis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Opis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Opis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $('.datepicker').datepicker({ format: 'dd.mm.yyyy', autoclose: true, todayHighlight: true, language: 'pl-PL' });
    </script>
}

Baza_zapasow/Views/WypozyczenieTV/Delete.cshtml
@model Baza_zapasow.Models.WypozyczenieTV

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>WypozyczenieTV</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DataWypozyczenia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataWypozyczenia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataZwrotu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataZwrotu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dodatkowo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dodatkowo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Opis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Opis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telewizory.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telewizory.Nazwa)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Baza_zapasow/Views/WypozyczenieTV/Details.cshtml
@model Baza_zapasow.Models.WypozyczenieTV

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>WypozyczenieTV</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DataWypozyczenia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataWypozyczenia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataZwrotu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataZwrotu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dodatkowo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dodatkowo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Opis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Opis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telewizory.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telewizory.Nazwa)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.WypozyczenieTVID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Baza_zapasow/Views/WypozyczenieTV/Edit.cshtml
@model Baza_zapasow.Models.WypozyczenieTV

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>WypozyczenieTV</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.WypozyczenieTVID)

        <div class="form-group">
            @Html.LabelFor(model => model.DataWypozyczenia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataWypozyczenia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataWypozyczenia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataZwrotu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataZwrotu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataZwrotu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TelewizorID, "TelewizorID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TelewizorID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TelewizorID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dodatkowo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dodatkowo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dodatkowo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Opis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Opis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Opis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Baza_zapasow/Views/WypozyczenieTV/Index.cshtml
@model IEnumerable<Baza_zapasow.Models.WypozyczenieTV>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<p>
    @Html.ActionLink("Dodaj telewizor", "Create", "Telewizory")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DataWypozyczenia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataZwrotu)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dodatkowo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Opis)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telewizory.Nazwa)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DataWypozyczenia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataZwrotu)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Dodatkowo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Opis)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telewizory.Nazwa)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.WypozyczenieTVID }) |
            @Html.ActionLink("Details", "Details", new { id=item.WypozyczenieTVID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.WypozyczenieTVID })
        </td>
    </tr>
}

</table>