Baza_zapasow/Models/Wypozyczenie.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza_zapasow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wypozyczenie
    {
        public int Wypozyczenie_Id { get; set; }
        public Nullable<int> Zgloszenie { get; set; }
        public System.DateTime Data_wypozyczenia { get; set; }
        public System.DateTime Data_zwrotu { get; set; }
        public int Uzytkownik_Id { get; set; }
        public string Nr_stacji { get; set; }
        public bool Zwrot { get; set; }
    
        public virtual Stacje Stacje { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
    }
}

Baza_zapasow/Controllers/UzytkownikController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Baza_zapasow.Models;
using iTextSharp.text.pdf;
using System.IO;
using System.Drawing.Printing;
using System.Diagnostics;
using Microsoft.Office.Interop.Word;
//using System.IO;

namespace Baza_zapasow.Controllers
{
    public class UzytkownikController : Controller
    {
        private Zapasy_bazaEntities db = new Zapasy_bazaEntities();
        

        // GET: Uzytkownik
        public ActionResult Index()
        {
            return View(db.Uzytkownik.ToList());
        }

        // GET: Uzytkownik/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uzytkownik uzytkownik = db.Uzytkownik.Find(id);
            if (uzytkownik == null)
            {
                return HttpNotFound();
            }
            return View(uzytkownik);
        }

        // GET: Uzytkownik/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Uzytkownik/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Uzytkownik_Id,Imie,Nazwisko,Adres,Kod_pocztowy,Miasto,Dowod,Nr_telefonu")] Uzytkownik uzytkownik)
        {
            if (ModelState.IsValid)
            {
                db.Uzytkownik.Add(uzytkownik);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(uzytkownik);
        }

        // GET: Uzytkownik/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uzytkownik uzytkownik = db.Uzytkownik.Find(id);
            if (uzytkownik == null)
            {
                return HttpNotFound();
            }
            return View(uzytkownik);
        }

        // POST: Uzytkownik/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Uzytkownik_Id,Imie,Nazwisko,Adres,Kod_pocztowy,Miasto,Dowod,Nr_telefonu")] Uzytkownik uzytkownik)
        {
            if (ModelState.IsValid)
            {
                db.Entry(uzytkownik).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(uzytkownik);
        }

        // GET: Uzytkownik/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uzytkownik uzytkownik = db.Uzytkownik.Find(id);
            if (uzytkownik == null)
            {
                return HttpNotFound();
            }
            return View(uzytkownik);
        }

        // POST: Uzytkownik/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Uzytkownik uzytkownik = db.Uzytkownik.Find(id);
            db.Uzytkownik.Remove(uzytkownik);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult PolaWPdf(int? id)
        {
            if (id == null)
            {
                new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Wypozyczenie wypozyczenie = db.Wypozyczenie.Find(id);

            string TemplatePdf = @"C:\PDF\WzorTokeny.pdf";
            string GotowyPdf = @"C:\PDF\umowa.pdf";

            using (var TemplateStream = new FileStream(TemplatePdf, FileMode.Open))
            using (var GotowyStream = new FileStream(GotowyPdf, FileMode.Create))
            {

                var pdfReader = new PdfReader(TemplateStream);
                var stamper = new PdfStamper(pdfReader, GotowyStream);

                var form = stamper.AcroFields;

                AcroFields af = stamper.AcroFields;

                List<string> ListaPDF = new List<string>();

                foreach (var field in af.Fields)
                {
                    ListaPDF.Add(field.Key + " " + field.Value);
                }

                //form.SetField("DataZawarcia", wypozyczenie.Data_wypozyczenia.ToString().Remove(10).ToUpper());
                //form.SetField("OsobaIT", "Bartosz Kozak".ToUpper());
                //form.SetField("Uzytkownik", wypozyczenie.Uzytkownik.ImieNazwisko.ToString().ToUpper());
                //form.SetField("KodMiasto", wypozyczenie.Uzytkownik.Kod_pocztowy.ToString().ToUpper());
                //form.SetField("Dowod", wypozyczenie.Uzytkownik.Dowod.ToString().ToUpper());
                //form.SetField("Adres", wypozyczenie.Uzytkownik.Adres.ToString().ToUpper());
                //form.SetField("NumerStacji", wypozyczenie.Nr_stacji.ToString().ToUpper());
                //form.SetField("DataZwrotu", wypozyczenie.Data_zwrotu.ToString().Remove(10).ToUpper());

                stamper.FormFlattening = true;

                stamper.Close();
                pdfReader.Close();

                //DoDrukarki(GotowyPdf);
                //ViewBag.Lista = ListaPDF;
                //Response.Redirect(Url.Action("Index", "Uzytkownik"));
                return View(ListaPDF);


            }
            
        }

        public ActionResult PobranyDOC(int? id)
        {

            //OpenFileDialog file = new OpenFileDialog();

            Application word = new Application();
            Document doc = new Document();

            object fileName = @"C:\PDF\umowa.doc";
            // Define an object to pass to the API for missing parameters
            object missing = System.Type.Missing;
            doc = word.Documents.Open(ref fileName,
                    ref missing, ref missing, ref missing, ref missing,
                    ref missing, ref missing, ref missing, ref missing,
                    ref missing, ref missing, ref missing, ref missing,
                    ref missing, ref missing, ref missing);

            String read = string.Empty;
            List<string> data = new List<string>();
            for (int i = 0; i < doc.Paragraphs.Count; i++)
            {
                string temp = doc.Paragraphs[i + 1].Range.Text.Trim();
                if (temp != string.Empty)
                    data.Add(temp);
            }
            ((_Document)doc).Close();
            ((_Application)word).Quit();
            return View(data);
        }

        public void FormatujListe(List<string> lista)
        {
            var znalezne = lista.Where(x => x.Contains("Panią"));

        }

        //public void UmowaDoc (int? id)
        //{
        //    Application word = new Application();
        //    Document doc = new Document();

        //    object fileName = @"C:\PDF\umowa.doc";
        //    // Define an object to pass to the API for missing parameters
        //    object missing = System.Type.Missing;
        //    doc = word.Documents.Open(ref fileName,
        //            ref missing, ref missing, ref missing, ref missing,
        //            ref missing, ref missing, ref missing, ref missing,
        //            ref missing, ref missing, ref missing, ref missing,
        //            ref missing, ref missing, ref missing);

        //    String read = string.Empty;
        //    List<string> data = new List<string>();
        //    for (int i = 0; i < doc.Paragraphs.Count; i++)
        //    {
        //        string temp = doc.Paragraphs[i + 1].Range.Text.Trim();
        //        if (temp != string.Empty)
        //            data.Add(temp);
        //    }
        //    ((_Document)doc).Close();
        //    ((_Application)word).Quit();
            
        //}
        public void DrukujUmowe (int? id)
        {
            if (id == null)
            {
                new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Wypozyczenie wypozyczenie = db.Wypozyczenie.Find(id);

            string TemplatePdf = @"C:\PDF\WzorTokeny.pdf";
            string GotowyPdf = @"C:\PDF\umowa" + DateTime.Now.ToString("dd-MM-yyyy") + ".pdf";

            using (var TemplateStream = new FileStream(TemplatePdf, FileMode.Open))
            using (var GotowyStream = new FileStream(GotowyPdf, FileMode.Create))
            {                

                var pdfReader = new PdfReader(TemplateStream);
                var stamper = new PdfStamper(pdfReader, GotowyStream);

                var form = stamper.AcroFields;

                AcroFields af = stamper.AcroFields;

                List<string> ListaPDF = new List<string>();
                
                foreach (var field in af.Fields)
                {
                    ListaPDF.Add(field.Key + " " + field.Value);                   
                }

                form.SetField("TokenaData", "11-30-2020r.");
                form.SetField("DataZawarcia", DateTime.Now.ToString("dd.MM.yyyy"));
                form.SetField("OsobaIT", "Bartosz Kozak".ToUpper());
                form.SetField("OsobaOdpowiedzialna", wypozyczenie.Uzytkownik.ImieNazwisko.ToString().ToUpper());
                form.SetField("Seria", wypozyczenie.Uzytkownik.Dowod.ToString().Remove(3,6).ToUpper());

Baza_zapasow/Controllers/WypozyczenieController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Baza_zapasow.Models;
using System.Dynamic;
using Baza_zapasow.ViewModels;

namespace Baza_zapasow.Controllers
{
    public class WypozyczenieController : Controller
    {
        private Zapasy_bazaEntities db = new Zapasy_bazaEntities();

        // GET: Wypozyczenie
        public ActionResult Index()
        {
            var wypozyczenie = db.Wypozyczenie.Include(w => w.Stacje).Include(w => w.Uzytkownik);
            return View(wypozyczenie.ToList());
        }

        // GET: Wypozyczenie/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wypozyczenie wypozyczenie = db.Wypozyczenie.Find(id);
            if (wypozyczenie == null)
            {
                return HttpNotFound();
            }
            return View(wypozyczenie);
        }

        // GET: Wypozyczenie/Create
        [Authorize]
        public ActionResult Create()
        {
            
            ViewBag.Nr_stacji = new SelectList(db.Stacje, "Nr_stacji", "Nr_stacji");
            ViewBag.Uzytkownik_Id = new SelectList(db.Uzytkownik, "Uzytkownik_Id", "ImieNazwisko");
            return View();
        }

        // POST: Wypozyczenie/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Wypozyczenie_Id,Zgloszenie,Data_wypozyczenia,Data_zwrotu,Uzytkownik_Id,Nr_stacji")] Wypozyczenie wypozyczenie)
        {
            if (ModelState.IsValid)
            {
                db.Wypozyczenie.Add(wypozyczenie);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Nr_stacji = new SelectList(db.Stacje, "Nr_stacji", "Nr_stacji", wypozyczenie.Nr_stacji);
            ViewBag.Uzytkownik_Id = new SelectList(db.Uzytkownik, "Uzytkownik_Id", "ImieNazwisko", wypozyczenie.Uzytkownik_Id);
            return View(wypozyczenie);
        }

        // GET: Wypozyczenie/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wypozyczenie wypozyczenie = db.Wypozyczenie.Find(id);
            if (wypozyczenie == null)
            {
                return HttpNotFound();
            }
            ViewBag.Nr_stacji = new SelectList(db.Stacje, "Nr_stacji", "Nr_stacji", wypozyczenie.Nr_stacji);
            ViewBag.Uzytkownik_Id = new SelectList(db.Uzytkownik, "Uzytkownik_Id", "ImieNazwisko", wypozyczenie.Uzytkownik_Id);
            return View(wypozyczenie);
        }

        // POST: Wypozyczenie/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Wypozyczenie_Id,Zgloszenie,Data_wypozyczenia,Data_zwrotu,Uzytkownik_Id,Nr_stacji,Zwrot")] Wypozyczenie wypozyczenie)
        {
            if (ModelState.IsValid)
            {
                db.Entry(wypozyczenie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Nr_stacji = new SelectList(db.Stacje, "Nr_stacji", "Nr_stacji", wypozyczenie.Nr_stacji);
            ViewBag.Uzytkownik_Id = new SelectList(db.Uzytkownik, "Uzytkownik_Id", "ImieNazwisko", wypozyczenie.Uzytkownik_Id);
            return View(wypozyczenie);
        }

        // GET: Wypozyczenie/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wypozyczenie wypozyczenie = db.Wypozyczenie.Find(id);
            if (wypozyczenie == null)
            {
                return HttpNotFound();
            }
            return View(wypozyczenie);
        }

        // POST: Wypozyczenie/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Wypozyczenie wypozyczenie = db.Wypozyczenie.Find(id);
            db.Wypozyczenie.Remove(wypozyczenie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Baza_zapasow/Views/Wypozyczenie/Create.cshtml
@model Baza_zapasow.Models.Wypozyczenie
@*@model Baza_zapasow.Models.Uzytkownik*@
@*@model Baza_zapasow.ViewModels.Baza_zapasowViewModel*@
@{
    ViewBag.Title = "Wypożyczenie sprzętu";
}

<h2>Nowe</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Wypozyczenie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Zgloszenie, "Numer zgłoszenia", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zgloszenie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zgloszenie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Data_wypozyczenia, "Data wypożyczenia", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data_wypozyczenia, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.Data_wypozyczenia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Data_zwrotu, "Data zwrotu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data_zwrotu, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.Data_zwrotu, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            <div class="form-group">
                @Html.LabelFor(model => model.Uzytkownik_Id, "Użytkownik", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-3">
                    @Html.DropDownList("Uzytkownik_Id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Uzytkownik_Id, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3">
                    @Html.ActionLink("Dodaj nowego", "Create", "Uzytkownik", new { area = "" }, new { @class = "btn btn-danger" })                   
                </div>

            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Nr_stacji, "Nr stacji", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Nr_stacji", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Nr_stacji, "", new { @class = "text-danger" })
            </div>
        </div>
        @* ------------------------------------------------Uzytkownik------------------------------------------------------------------------------- *@
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć do listy", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $('.datepicker').datepicker({ format: 'dd.mm.yyyy', autoclose: true, todayHighlight: true, language: 'pl-PL' });
    </script>
}

Baza_zapasow/Views/Wypozyczenie/Delete.cshtml
@model Baza_zapasow.Models.Wypozyczenie

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Wypozyczenie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Zgloszenie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zgloszenie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data_wypozyczenia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data_wypozyczenia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data_zwrotu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data_zwrotu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stacje.Uwagi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stacje.Uwagi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Uzytkownik.Imie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Uzytkownik.Imie)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Baza_zapasow/Views/Wypozyczenie/Details.cshtml
@model Baza_zapasow.Models.Wypozyczenie

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Wypozyczenie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Zgloszenie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zgloszenie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data_wypozyczenia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data_wypozyczenia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data_zwrotu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data_zwrotu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stacje.Uwagi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stacje.Uwagi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Uzytkownik.Imie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Uzytkownik.Imie)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Wypozyczenie_Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Baza_zapasow/Views/Wypozyczenie/Edit.cshtml
@model Baza_zapasow.Models.Wypozyczenie

@{
    ViewBag.Title = "Edycja";
}

<h2>Edycja</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Wypozyczenie_Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Zgloszenie, "Numer zgłoszenia", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zgloszenie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zgloszenie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Data_wypozyczenia, "Data wypożyczenia",  htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data_wypozyczenia, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.Data_wypozyczenia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Data_zwrotu, "Data zwrotu", htmlAttributes: new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data_zwrotu, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.Data_zwrotu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Uzytkownik_Id, "Użytkownik", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Uzytkownik_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Uzytkownik_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nr_stacji, "Nr stacji", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Nr_stacji", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Nr_stacji, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zwrot, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zwrot, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zwrot, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script type="text/javascript">
    $('.datepicker').datepicker({ format: 'dd.mm.yyyy', autoclose: true, todayHighlight: true, todayBtn: true, language: 'pl'});
</script>
}

Baza_zapasow/Views/Wypozyczenie/Index.cshtml
@model IEnumerable<Baza_zapasow.Models.Wypozyczenie>

@{
    ViewBag.Title = "Wypożyczenia";
}

<h2>Wypożyczenia</h2>

<p>
    @*@Html.ActionLink("Create New", "Create")*@
</p>
<table class="table table-bordered">
    <tr>
        <th>
            <p>Numer zgłoszenia</p>
        </th>
        <th>
            <p>Data wypożyczenia</p>
        </th>
        <th>
            <p>Data zwrotu</p>
        </th>
        <th>
            <p>Numer stacji</p>
        </th>
        <th>
            <p>Użytkownik</p>
        </th>
        <th>
            <p class="text-center">Zwrot</p>
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Zgloszenie)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Data_wypozyczenia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Data_zwrotu)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Stacje.Nr_stacji)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Uzytkownik.ImieNazwisko)
        </td>
        <td class="text-center">
            @Html.DisplayFor(modelItem => item.Zwrot)
        </td>
        <td>
            @Html.ActionLink("Edytuj", "Edit", new { id=item.Wypozyczenie_Id }) |
            @*@Html.ActionLink("Details", "Details", new { id=item.Wypozyczenie_Id }) |*@
            @Html.ActionLink("Usuń", "Delete", new { id=item.Wypozyczenie_Id })
        </td>
    </tr>
}

</table>